export const avataaars = [
  { name: "Jocelyn" },
  { name: "Valentina" },
  { name: "Katherine" },
  { name: "Jude" },
  { name: "Aiden" },
  { name: "Alexander" },
  { name: "George" },
  { name: "Aidan" },
  { name: "Luis" },
  { name: "Ryan" },
  { name: "Cale" },
  { name: "Riley" },
  { name: "Amaya" },
  { name: "Brooklynn" },
  { name: "Avery" },
];
