export const avataaars = [
  { name: "avatar-one" },
  { name: "avatar-two" },
  { name: "avatar-three" },
  { name: "avatar-four" },
  { name: "avatar-five" },
  { name: "avatars-six" },
  { name: "avatar-seven" },
  { name: "avatar-eight" },
  { name: "avatar-nine" },
  { name: "avatars-ten" },
  { name: "avatar-eleven" },
  { name: "avatar-twelve" },
  { name: "avatar-thirteen" },
  { name: "avatar-fourteen" },
  { name: "avatar-fifteen" },
];
